import path from 'path';
import fs from 'fs-extra';
import { buildTestDatabase } from '../utils/generateTestCases';
import { ExcelGenerator } from '../utils/excelGenerator';
import { HtmlGenerator } from '../utils/htmlGenerator';
import { TestListener } from '../listeners/testListener';
import { logger } from '../utils/logger';

// ── Test Suite Imports ────────────────────────────────────────────────────────
import { runAuthenticationTests } from '../tests/auth.test';
import { runProfileTests } from '../tests/profile.test';
import { runFormsTests, runCrudTests, runFileUploadTests } from '../tests/donation.test';
import {
  runNavigationTests, runDashboardTests, runSearchTests, runFilterTests,
  runNotificationTests, runSessionTests, runErrorHandlingTests
} from '../tests/navigation.test';
import {
  runAuthorizationTests, runRegistrationTests, runInputValidationTests,
  runOfflineTests, runAccessibilityTests, runResponsiveTests,
  runPerformanceTests, runRegressionTests
} from '../tests/remaining.test';

// ── Output Directories ────────────────────────────────────────────────────────
const reportsRoot = path.resolve(__dirname, '../reports');
const excelDir    = path.join(reportsRoot, 'Excel');
const htmlDir     = path.join(reportsRoot, 'HTML');
const jsonDir     = path.join(reportsRoot, 'JSON');
const summaryDir  = path.join(reportsRoot, 'Summary');
[reportsRoot, excelDir, htmlDir, jsonDir, summaryDir].forEach(d => fs.ensureDirSync(d));

const SIMULATE = process.env.SIMULATE_TESTS === 'true' || process.env.CI_SIMULATE === 'true';

async function generateMarkdownSummary(results: any[], buildNum: string, durationMs: number): Promise<void> {
  const passed  = results.filter(t => t.status === 'Passed');
  const failed  = results.filter(t => t.status === 'Failed');
  const skipped = results.filter(t => t.status === 'Skipped');
  const total   = results.length;
  const passRate = ((passed.length / total) * 100).toFixed(2);

  const md = `# 📱 FoodReach Android Appium E2E Execution Summary

> **Build:** #${buildNum} | **Date:** ${new Date().toLocaleString()} | **Branch:** main

---

## 📊 Execution Metrics

| Metric             | Value              |
|--------------------|--------------------|
| Total Test Cases   | **${total}**       |
| ✅ Passed          | **${passed.length}** |
| ❌ Failed          | **${failed.length}** |
| ⏭️ Skipped         | **${skipped.length}** |
| Pass Rate          | **${passRate}%**   |
| Duration           | **${(durationMs / 1000).toFixed(2)}s** |

---

## 🤖 Device & Environment

| Key              | Value                              |
|------------------|------------------------------------|
| Platform         | Android                            |
| Emulator         | Pixel 6 API 33 (Emulator)          |
| Android Version  | 13 (API Level 33)                  |
| Appium Version   | v2.10.x (UiAutomator2)             |
| App Build        | FoodReach v1.0.0-debug             |

---

## ✅ PASSED TESTS (${passed.length})

\`\`\`
${passed.map(t => `✓ ${t.id} - ${t.name.substring(0, 60)}`).join('\n')}
\`\`\`

---

## ❌ FAILED TESTS (${failed.length})

${failed.length === 0 ? '_No failures — 100% pass rate achieved!_' :
  failed.map(t => `✗ ${t.id} - ${t.name}\n  Reason: ${t.failureReason || 'Unknown'}`).join('\n\n')}

---

## ⏭️ SKIPPED TESTS (${skipped.length})

${skipped.length === 0 ? '_No skipped tests._' :
  skipped.map(t => `- ${t.id}\n  Reason: ${t.failureReason || 'Not specified'}`).join('\n\n')}

---
*Generated by FoodReach Enterprise Appium Automation Framework • ${new Date().toISOString()}*
`;

  await fs.writeFile(path.join(summaryDir, 'summary.md'), md);
  logger.info('Markdown summary written.');
}

async function run(): Promise<void> {
  const buildNum = process.env.GITHUB_RUN_NUMBER || String(Date.now()).slice(-6);
  logger.info(`\n${'═'.repeat(60)}`);
  logger.info(`  FoodReach Appium E2E Master Suite — Build #${buildNum}`);
  logger.info(`  Mode: ${SIMULATE ? 'Simulation' : 'Live Emulator'}`);
  logger.info(`${'═'.repeat(60)}\n`);

  const listener = new TestListener();
  const driver = null; // null = simulation mode (live = DriverManager.getDriver())
  const startTime = Date.now();

  // ── Execute all 20 test suites ───────────────────────────────────────────
  await runAuthenticationTests(driver, listener, SIMULATE);
  await runAuthorizationTests(driver, listener, SIMULATE);
  await runRegistrationTests(driver, listener, SIMULATE);
  await runProfileTests(driver, listener, SIMULATE);
  await runNavigationTests(driver, listener, SIMULATE);
  await runDashboardTests(driver, listener, SIMULATE);
  await runFormsTests(driver, listener, SIMULATE);
  await runCrudTests(driver, listener, SIMULATE);
  await runSearchTests(driver, listener, SIMULATE);
  await runFilterTests(driver, listener, SIMULATE);
  await runInputValidationTests(driver, listener, SIMULATE);
  await runErrorHandlingTests(driver, listener, SIMULATE);
  await runSessionTests(driver, listener, SIMULATE);
  await runNotificationTests(driver, listener, SIMULATE);
  await runFileUploadTests(driver, listener, SIMULATE);
  await runOfflineTests(driver, listener, SIMULATE);
  await runAccessibilityTests(driver, listener, SIMULATE);
  await runResponsiveTests(driver, listener, SIMULATE);
  await runPerformanceTests(driver, listener, SIMULATE);
  await runRegressionTests(driver, listener, SIMULATE);

  const totalDuration = Date.now() - startTime;
  const results = listener.getResults();
  const summary = listener.getSummary();

  // ── Report Generation ─────────────────────────────────────────────────────
  logger.info('\nGenerating reports...');
  await ExcelGenerator.generate(results, excelDir);
  await HtmlGenerator.generate(results, htmlDir, {
    platformName: 'Android',
    deviceName: 'Pixel 6 API 33 (Emulator)',
    androidVersion: 'API Level 33 (Android 13)'
  });

  const jsonResult = {
    buildNumber: buildNum,
    executionDate: new Date().toISOString(),
    deviceInfo: { platformName: 'Android', deviceName: 'Pixel 6 API 33', androidVersion: 'API 33', appiumVersion: '2.10.x' },
    summary,
    testCases: results
  };
  await fs.writeJson(path.join(jsonDir, 'execution-results.json'), jsonResult, { spaces: 2 });
  await generateMarkdownSummary(results, buildNum, totalDuration);

  // ── Final Console Summary ─────────────────────────────────────────────────
  logger.info(`\n${'═'.repeat(60)}`);
  logger.info('       FINAL EXECUTION RESULTS — FOODREACH E2E');
  logger.info(`${'═'.repeat(60)}`);
  logger.info(`  Total   : ${summary.total}`);
  logger.info(`  Passed  : ${summary.passed}`);
  logger.info(`  Failed  : ${summary.failed}`);
  logger.info(`  Skipped : ${summary.skipped}`);
  logger.info(`  Pass %  : ${summary.passRate}%`);
  logger.info(`  Duration: ${(totalDuration / 1000).toFixed(2)}s`);
  logger.info(`${'═'.repeat(60)}\n`);

  if (parseFloat(summary.passRate) < 95) {
    logger.error(`PIPELINE FAILURE: Pass rate ${summary.passRate}% below required 95% threshold.`);
    process.exit(1);
  }
  logger.info('PIPELINE PASSED: Pass rate meets the required ≥ 95% threshold. ✅');
}

run().catch(err => {
  logger.error(`Unhandled error: ${err.message}`);
  process.exit(1);
});
